import type { Metadata } from "next";
import WaitlistForm from "@/components/waitlist-form";

export const metadata: Metadata = {
  title: "AM vs Devin — Autonomous Digital Worker vs AI Software Engineer | helloam.bot",
  description:
    "Compare AM and Devin side by side. See how an autonomous digital worker that spans dev, support, and ops differs from a coding-focused AI software engineer.",
  keywords: [
    "AM vs Devin",
    "Devin alternative",
    "Devin AI comparison",
    "AI software engineer comparison",
    "autonomous AI agent vs Devin",
    "helloam.bot",
  ],
  metadataBase: new URL("https://helloam.bot"),
  alternates: {
    canonical: "https://helloam.bot/compare/am-vs-devin",
  },
  openGraph: {
    title: "AM vs Devin — Autonomous Digital Worker vs AI Software Engineer",
    description:
      "AM and Devin are both autonomous AI agents — but they solve different problems. Compare capabilities, scope, and fit for your team.",
    url: "https://helloam.bot/compare/am-vs-devin",
    siteName: "helloam.bot",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AM vs Devin — Autonomous Digital Worker vs AI Software Engineer",
    description:
      "Both AM and Devin work autonomously. Here's what separates them — and which one fits your team.",
    images: ["/og-image.png"],
  },
};

const jsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "@id": "https://helloam.bot/compare/am-vs-devin#faq",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is the main difference between AM and Devin?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Devin is an AI software engineer focused on writing and shipping code autonomously. AM is a cross-functional digital worker: it handles software tasks (tickets, PRs, code review) and also covers customer support triage, on-call incident response, and cross-team coordination — without requiring separate tools for each function.",
        },
      },
      {
        "@type": "Question",
        name: "Can AM write code like Devin?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. AM picks up tickets from Jira or Linear, reads the codebase, writes the implementation, generates tests, and opens a PR — the same flow as Devin. The difference is AM also handles the surrounding work: routing the ticket, triaging the on-call alert that triggered it, and answering the customer questions generated by the bug.",
        },
      },
      {
        "@type": "Question",
        name: "Is AM a Devin alternative?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "AM is an alternative to Devin for teams that need more than a coding agent. If your bottleneck is purely software development throughput, Devin is purpose-built for that. If your team also needs autonomous support, triage, and ops coverage, AM handles all of it in one worker.",
        },
      },
      {
        "@type": "Question",
        name: "How does AM pricing compare to Devin?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "AM is currently in early access with free pilot access available. Team pricing starts from $149/seat/month. Devin's pricing is usage-based starting at $500/month. For teams needing cross-functional coverage, AM delivers more scope per dollar.",
        },
      },
    ],
};

const tableRows = [
  { dimension: "Autonomous task execution", am: "yes", devin: "yes" },
  { dimension: "Ticket → Pull Request", am: "yes", devin: "yes" },
  { dimension: "Code review", am: "yes", devin: "partial" },
  { dimension: "Customer support triage", am: "yes", devin: "no" },
  { dimension: "On-call incident response", am: "yes", devin: "no" },
  { dimension: "Cross-team coordination", am: "yes", devin: "no" },
  { dimension: "Multi-function in one worker", am: "yes", devin: "no" },
  { dimension: "Free early access", am: "yes", devin: "no" },
];

function Cell({ value }: { value: string }) {
  if (value === "yes") return <span className="text-[#00E5FF] font-semibold">✓ Yes</span>;
  if (value === "partial") return <span className="text-yellow-400 font-semibold">~ Partial</span>;
  return <span className="text-gray-500">✗ No</span>;
}

export default function AmVsDevinPage() {
  return (
    <main className="min-h-screen bg-[#0A0A0A] text-white">
      {/* JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Hero */}
      <section className="max-w-4xl mx-auto px-6 pt-24 pb-16 text-center">
        <p className="text-sm font-semibold uppercase tracking-widest text-[#00E5FF] mb-4">
          Comparison
        </p>
        <h1 className="text-4xl md:text-5xl font-bold leading-tight mb-6">
          AM vs Devin
        </h1>
        <p className="text-lg text-gray-400 max-w-2xl mx-auto">
          Both are autonomous AI agents. Devin is an AI software engineer. AM is a digital worker
          that handles software <em>and</em> the work surrounding it — support, triage, and
          coordination — without you stitching tools together.
        </p>
      </section>

      {/* Verdict cards */}
      <section className="max-w-4xl mx-auto px-6 pb-16 grid gap-4 md:grid-cols-3">
        {[
          { label: "AM wins on", point: "Cross-functional scope — dev, support, and ops in one worker" },
          { label: "AM wins on", point: "Incident triage and on-call response built in" },
          { label: "AM wins on", point: "Pricing — free early access, team plans from $149/seat" },
        ].map(({ label, point }, i) => (
          <div key={i} className="rounded-xl border border-[#00E5FF]/20 bg-[#00E5FF]/5 p-5">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#00E5FF] mb-2">{label}</p>
            <p className="text-sm text-gray-300 leading-relaxed">{point}</p>
          </div>
        ))}
      </section>

      {/* Comparison Table */}
      <section className="max-w-4xl mx-auto px-6 pb-20">
        <h2 className="text-2xl font-bold mb-6 text-center">Feature comparison</h2>
        <div className="overflow-x-auto rounded-xl border border-white/10">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/10 bg-white/5">
                <th className="text-left px-6 py-4 font-semibold text-gray-400">Capability</th>
                <th className="px-6 py-4 font-bold text-[#00E5FF] border-l-2 border-[#00E5FF]/40 bg-[#00E5FF]/5">
                  AM
                </th>
                <th className="px-6 py-4 font-semibold text-gray-400">Devin</th>
              </tr>
            </thead>
            <tbody>
              {tableRows.map(({ dimension, am, devin }, i) => (
                <tr key={i} className="border-b border-white/5 hover:bg-white/3 transition-colors">
                  <td className="px-6 py-4 text-gray-300">{dimension}</td>
                  <td className="px-6 py-4 text-center border-l-2 border-[#00E5FF]/20 bg-[#00E5FF]/3">
                    <Cell value={am} />
                  </td>
                  <td className="px-6 py-4 text-center">
                    <Cell value={devin} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="mt-3 text-xs text-gray-500 text-center">
          Based on publicly available information. Last reviewed April 2026.
        </p>
      </section>

      {/* Who is Devin for */}
      <section className="max-w-4xl mx-auto px-6 pb-16">
        <div className="grid md:grid-cols-2 gap-8">
          <div className="rounded-xl border border-white/10 bg-white/5 p-6">
            <h2 className="text-xl font-bold mb-3">Who is Devin for?</h2>
            <p className="text-gray-400 text-sm leading-relaxed">
              Devin is purpose-built for engineering teams that need to increase software development
              throughput. It excels at end-to-end coding tasks — reading a spec, writing the code,
              and shipping a working PR. If your only bottleneck is developer capacity and you have
              separate tools for support, ops, and triage, Devin fits that gap.
            </p>
          </div>
          <div className="rounded-xl border border-[#00E5FF]/20 bg-[#00E5FF]/5 p-6">
            <h2 className="text-xl font-bold mb-3">Who is AM for?</h2>
            <p className="text-gray-400 text-sm leading-relaxed">
              AM is for teams that are stretched across functions — engineering, support, and ops —
              and want one digital worker to handle all of it without wrangling a stack of
              single-purpose tools. AM codes, triages, responds, and coordinates. One worker,
              every function.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-3xl mx-auto px-6 pb-20">
        <h2 className="text-2xl font-bold mb-8 text-center">Common questions</h2>
        <div className="space-y-6">
          {jsonLd.mainEntity.map((qa, i) => (
            <div key={i} className="border-b border-white/10 pb-6">
              <h3 className="font-semibold text-white mb-2">{qa.name}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{qa.acceptedAnswer.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-xl mx-auto px-6 pb-24 text-center">
        <h2 className="text-2xl font-bold mb-4">Try AM free</h2>
        <p className="text-gray-400 mb-8">
          Join the waitlist and get early pilot access — no credit card required.
        </p>
        <WaitlistForm />
      </section>
    </main>
  );
}
